name: CI
on:
  pull_request:
jobs:
  cabal:
    name: ${{ matrix.os }} / ghc-${{ matrix.ghc }}
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, macOS-latest, windows-latest]
        cabal: ["3.2"]
        ghc: ["8.6.5", "8.8.4", "8.10.2"]
        # Newer versions of GHC are broken on Windows:
        # https://gitlab.haskell.org/ghc/ghc/-/issues/17926
        exclude:
          - os: windows-latest
            ghc: "8.8.4"
          - os: windows-latest
            ghc: "8.10.2"
    steps:
      - name: Clone Repository
        uses: actions/checkout@v2

      - name: Install Windows Dependencies
        if: matrix.os == 'windows-latest'
        run: dotnet add package Icu4c.Win.Full.Lib --version 59.1.15

      - name: Install macOS Dependencies
        if: matrix.os == 'macOS-latest'
        run: |
          brew install icu4c
          brew link icu4c --force

      - name: Setup Haskell
        id: setup-haskell-cabal
        uses: actions/setup-haskell@v1.1.3
        with:
          ghc-version: ${{ matrix.ghc }}
          cabal-version: ${{ matrix.cabal }}

      - name: Configure and Freeze for Cache
        run: |
          cabal configure --enable-tests --enable-benchmarks --test-show-details=direct
          cabal freeze

      - name: Cache ~/.cabal/store
        uses: actions/cache@v1
        with:
          path: ${{ steps.setup-haskell-cabal.outputs.cabal-store }}
          key: ${{ runner.os }}-${{ matrix.ghc }}-${{ hashFiles('cabal.project.freeze') }}

      - name: Build
        run: cabal build '--build-log=logs/$pkgid'

      - name: Test
        run: cabal test

      - name: Upload Build Logs on Failure
        uses: actions/upload-artifact@v2
        if: failure()
        with:
          name: logs-${{ matrix.os }}-ghc${{ matrix.ghc }}
          path: logs/
